server:
 port: 6896

spring:
 mvc:
   view:
     prefix: /WEB-INF/jsp/
     suffix: .jsp
 application:
   name: consumer

eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka/
 instance:
   prefer-ip-address: true
   appname: consumer