server:
  port: 6791

spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql://localhost:3306/score?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yln1430899710

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    appname: eureka.provider

mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.example.clientStudent.entity